name: Update Image
on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    name: Update Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Docker Repository
        uses: dhet/docker-repo-scan-action@master
        with:
          image: debezium/connect
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          max-age-minutes: 15
        id: scan
      - name: Build + Deploy
        run: "./build_and_deploy.sh ${{ steps.scan.outputs.tags }}"
